### ISSUE TITLE
Hover highlight (red overlay) on rasters might be confusing

### ISSUE THREAD

**Issue by j08lue** [NASA-IMPACT/veda-interactive-emission-plumes#1]
Currently, when you hover on a plume, it gets highlighted by adding a semi-transparent red overlay on the raster.

Since the resulting shading is actually valid-ish within the color map, that might be a bit confusing when a user wants to look up the color range in the color map legend.

![screenshot-2022-08-26](https://github.com/NASA-IMPACT/veda-interactive-emission-plumes/assets/3404817/167ff9ef-c91a-4e61-9008-caf66ca88695)

Just thinking - if we could for example highlight on hover by changing the outline (boundary polygon) instead of adding an overlay, that would always preserve the raster colors.

Please feel free to close this as nitpick, though. 😄

**Comment by jsignell** [comment]
I caught this one in #2
